In [5]:
import pandas as pd
import seaborn as sbs
import matplotlib.pyplot as plt
import numpy as np 
from sklearn.preprocessing import StandardScaler,MinMaxScaler,LabelEncoder
from sklearn.linear_model import LinearRegression,LogisticRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,root_mean_squared_error,mean_absolute_error,r2_score

In [6]:
df=pd.read_csv(r'used_phone_price_prediction_1M.csv')

In [7]:
df

,brand,model,release_year,ram_gb,storage_gb,screen_size_inches,battery_capacity,processor_score,camera_score,os_type,...,body_damage,repair_history,water_damage,city_tier,seller_type,warranty_remaining_months,box_available,charger_available,market_demand_score,resale_price
0,Realme,Realme GT,2025,4,256,6.93,4130,47,100,Android,...,0,0,0,Tier1,Individual,11,1,1,99,47891.46
1,Samsung,Galaxy S21,2024,16,64,6.29,5558,81,67,Android,...,0,0,0,Tier3,Store,8,1,0,64,17663.21
2,Apple,iPhone 11,2022,4,128,5.52,5945,59,67,iOS,...,0,0,0,Tier1,Individual,0,0,1,68,67268.20
3,Google,Pixel 6,2024,16,512,5.99,5767,84,57,Android,...,0,0,1,Tier1,Store,11,1,1,50,12626.26
4,Google,Pixel 7,2021,4,128,6.59,5336,98,44,Android,...,0,0,0,Tier3,Store,24,1,1,66,20662.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,Samsung,Galaxy A54,2023,6,128,6.61,6358,99,63,Android,...,0,0,0,Tier3,Store,11,1,1,95,56194.05
999996,Samsung,Galaxy A54,2021,16,512,6.19,6142,63,43,Android,...,0,0,0,Tier3,Store,11,0,1,65,2040.32
999997,Apple,iPhone 15,2022,4,256,5.97,5874,79,49,iOS,...,0,0,0,Tier2,Individual,14,0,1,99,31236.16
999998,Apple,iPhone 13,2023,12,512,6.73,5220,53,56,iOS,...,0,0,0,Tier3,Store,17,1,1,57,16288.20
999999,Realme,Realme GT,2020,16,256,6.16,6463,91,51,Android,...,0,1,0,Tier2,Individual,10,1,1,83,9819.03

In [8]:
df=df.drop(columns=['brand','model','os_type','condition','seller_type','city_tier'])

In [9]:
df.dtypes

release_year                   int64
ram_gb                         int64
storage_gb                     int64
screen_size_inches           float64
battery_capacity               int64
processor_score                int64
camera_score                   int64
has_5g                         int64
original_price                 int64
purchase_year                  int64
age_months                     int64
usage_hours_per_day          float64
battery_health                 int64
screen_cracked                 int64
body_damage                    int64
repair_history                 int64
water_damage                   int64
warranty_remaining_months      int64
box_available                  int64
charger_available              int64
market_demand_score            int64
resale_price                 float64
dtype: object

In [10]:
df.isnull().sum()

release_year                 0
ram_gb                       0
storage_gb                   0
screen_size_inches           0
battery_capacity             0
processor_score              0
camera_score                 0
has_5g                       0
original_price               0
purchase_year                0
age_months                   0
usage_hours_per_day          0
battery_health               0
screen_cracked               0
body_damage                  0
repair_history               0
water_damage                 0
warranty_remaining_months    0
box_available                0
charger_available            0
market_demand_score          0
resale_price                 0
dtype: int64

In [ ]:
for i in df.columns:
    sbs.boxplot(df[i])
    plt.show()

In [11]:
label=LabelEncoder()
labels={}
for i in df.columns:
    if df[i].dtypes=='object':
        df[i]=label.fit_transform(df[i])
        labels=list(enumerate(list(label.classes_)))

In [12]:
labels

{}

In [13]:
mms=MinMaxScaler()

In [14]:
X=df.drop(['resale_price'],axis=1)
Y= df.resale_price

In [15]:
X_norm=mms.fit_transform(X)

In [16]:
std=StandardScaler()

In [17]:
X_std= std.fit_transform(X)

In [ ]:
X.plot()

In [ ]:
plt.plot(X_norm,label=X.columns)
plt.legend()
plt.show()

In [ ]:
plt.plot(X_std,label=X.columns)
plt.legend()
plt.show()

In [18]:
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=42)
nx_train,nx_test,ny_train,ny_test=train_test_split(X_norm,Y,test_size=0.3,random_state=42)
sx_train,sx_test,sy_train,sy_test=train_test_split(X_std,Y,test_size=0.3,random_state=42)

In [19]:
lr=LinearRegression()

In [20]:
lr.fit(x_train,y_train)

LinearRegression()

In [21]:
lr.fit(nx_train,ny_train)

LinearRegression()

In [22]:
lr.fit(sx_train,sy_train)

LinearRegression()

In [23]:
pred=lr.predict(x_test)

C:\Users\user\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2684: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(

In [24]:
npred=lr.predict(nx_test)

In [25]:
spred=lr.predict(sx_test)

In [26]:
lr.score(x_train,y_train)

C:\Users\user\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2684: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(

-3480924840.9215226

In [27]:
lr.score(x_test,y_test)

C:\Users\user\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2684: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(

-3453629702.334059

In [28]:
lr.score(nx_train,ny_train)

0.20699652835019322

In [29]:
lr.score(nx_test,ny_test)

0.21121567921236795

In [30]:
lr.score(sx_train,sy_train)

0.771241469740496

In [31]:
lr.score(sx_test,sy_test)

0.7719991620642463

In [32]:
lr=LinearRegression()
lr.fit(x_train,y_train)
npred=lr.predict(x_test)
lr.score(x_test,y_test)
print('mae=',mean_absolute_error(y_test,pred))
print('rmse=',root_mean_squared_error(y_test,pred))
print('mse=', mean_squared_error(y_test,pred))
print('r2_square=' ,lr.score(x_test,y_test))

mae= 876456117.883834
rmse= 981966909.55229
mse= 9.642590114556753e+17
r2_square= 0.7719991620642463

In [33]:
lr=LinearRegression()
lr.fit(nx_train,ny_train)
npred=lr.predict(nx_test)
lr.score(nx_test,ny_test)
print('mae=',mean_absolute_error(y_test,npred))
print('rmse=',root_mean_squared_error(y_test,npred))
print('mse=', mean_squared_error(y_test,npred))
print('r2_square=' ,lr.score(nx_test,ny_test))

mae= 5729.937818086947
rmse= 7978.609123010706
mse= 63658203.537789665
r2_square= 0.7719991620642461

In [34]:
lr=LinearRegression()
lr.fit(nx_train,sy_train)
npred=lr.predict(sx_test)
lr.score(sx_test,sy_test)
print('mae=',mean_absolute_error(y_test,npred))
print('rmse=',root_mean_squared_error(y_test,npred))
print('mse=', mean_squared_error(y_test,npred))
print('r2_square=' ,lr.score(nx_test,ny_test))

mae= 34016.199055636
rmse= 43919.35553798055
mse= 1928909790.8715425
r2_square= 0.7719991620642461

In [35]:
pd.DataFrame({'actual': y_test,'predicted':pred,'normalised':npred,'standardized':spred})

          actual     predicted    normalised  standardized
987231  18143.48  8.835453e+08 -19894.147232  16704.186071
79954   44779.54  1.194765e+09  58980.954961  40312.115372
567130  27081.71  1.415469e+09  48230.156789  36881.965057
500891  15294.01  1.404841e+09  29281.578850  31162.369774
55399   17980.52  1.005200e+09  -5981.864634  20968.600187
...          ...           ...           ...           ...
463299  10761.87  4.186490e+08 -63957.154234   3905.449519
728324  15664.05  8.587131e+08  -8445.326311  20143.916833
76260   35993.09  1.528658e+09  58479.405746  39876.479778
77813   31271.17  1.488571e+09  20413.347232  28432.751769
718205   8980.14  1.949047e+08 -41342.814166  10946.951082

[300000 rows x 4 columns]

In [ ]:
K=1                # number of variables
n=X.shape[0]       # number of X rows
Adj_R2s=[]         # empty list

for i in range(len(X.columns)):
    Rx= X.iloc[:,0:K]
    x_train,x_test,y_train,y_test= train_test_split(Rx,Y,test_size=0.25,random_state=42)
    lr=LinearRegression()
    lr.fit(x_train,y_train)         # will get coefficient and intercept value to get prediction
    r2= lr.score(x_test,y_test)     # r2 value
    adj_r2= 1-(1-r2)*(n-1)/(n-K-1)  # adjusted R2 value
    Adj_R2s.append(adj_r2)          
    K+=1

In [ ]:
Adj_R2s

In [ ]:
sbs.lineplot(Adj_R2s,marker='o')

In [ ]:
df.columns

In [ ]:
plt.figure(figsize=(20,20))
sbs.heatmap(df.corr(),annot=True)

In [ ]:
Adj=df.drop(columns=['usage_hours_per_day','screen_cracked','purchase_year','release_year', 'screen_size_inches', 'camera_score', 'has_5g',])

In [ ]:
df

In [ ]:
x_train,x_test,y_train,y_test= train_test_split(Adj,Y,test_size=0.3,random_state=42)
lr=LinearRegression()
lr.fit(x_train,y_train)         # will get coefficient and intercept value to get prediction
r2= lr.score(x_test,y_test)

In [ ]:
r2

In [ ]:
from sklearn.linear_model import Ridge,Lasso,ElasticNet

In [ ]:
l1=Ridge()
l2=Lasso()
EN=ElasticNet()

In [ ]:
l1.fit(x_train,y_train)
print('L1 TRAINING R2 VALUE:', l1.score(x_train,y_train))
print('L1 TESTING R2 VALUE: ', l1.score(x_test,y_test))

In [ ]:
l2.fit(x_train,y_train)
print('L1 TRAINING R2 VALUE:', l2.score(x_train,y_train))
print('L1 TESTING R2 VALUE: ', l2.score(x_test,y_test))

In [ ]:
EN.fit(x_train,y_train)
print('L1 TRAINING R2 VALUE:', EN.score(x_train,y_train))
print('L1 TESTING R2 VALUE: ', EN.score(x_test,y_test))

In [ ]:
L1_pred=l1.predict(x_test)
L2_pred=l2.predict(x_test)
EN_pred=EN.predict(x_test)

In [ ]:
sbs.regplot(x=y_test,y=L1_pred)

In [ ]:
sbs.regplot(x=y_test,y=L2_pred)

In [ ]:
sbs.regplot(x=y_test,y=EN_pred)

In [ ]:
import pickle

In [ ]:
pickle.dump(lr,open('model.pkl','wb'))
pickle.dump(list(X.columns),open('columns.pkl','wb'))